// Code generated by "stringer -type=OutputEnum -linecomment -output output_enum_string.go"; DO NOT EDIT.

package logging

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OutputUnknown-0]
	_ = x[OutputStdout-1]
	_ = x[OutputStderr-2]
	_ = x[OutputFile-3]
}

const _OutputEnum_name = "unknownstdoutstderrfile"

var _OutputEnum_index = [...]uint8{0, 7, 13, 19, 23}

func (i OutputEnum) String() string {
	if i < 0 || i >= OutputEnum(len(_OutputEnum_index)-1) {
		return "OutputEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OutputEnum_name[_OutputEnum_index[i]:_OutputEnum_index[i+1]]
}
