// Code generated by "stringer -type=HeaderTypeEnum -linecomment -output header_type_enum_string.go"; DO NOT EDIT.

package libcpio

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[HeaderTypeUnknown-0]
	_ = x[HeaderTypeCPIO-1]
	_ = x[HeaderTypeXZ-2]
	_ = x[HeaderTypeGZ-3]
}

const _HeaderTypeEnum_name = "unknowncpioxzgz"

var _HeaderTypeEnum_index = [...]uint8{0, 7, 11, 13, 15}

func (i HeaderTypeEnum) String() string {
	if i < 0 || i >= HeaderTypeEnum(len(_HeaderTypeEnum_index)-1) {
		return "HeaderTypeEnum(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HeaderTypeEnum_name[_HeaderTypeEnum_index[i]:_HeaderTypeEnum_index[i+1]]
}
